### ISSUE TITLE
Sidebar shouldn't list instructions for both daemon and wings

### ISSUE THREAD

**Issue by iamkubi** [pterodactyl/documentation#211]
![image](https://user-images.githubusercontent.com/6176191/80757251-b14ed200-8ae8-11ea-9cc6-626fb6683ecd.png)

If you follow the instructions from top to bottom you will install both 0.6 and 0.7 daemon.  I think these two sections should be combined in a single dropdown rather than separate items.

People are doing this, e.g.:
```
KanameToday at 1:43 PM
Daemon work but wings dont want start
i've Daemon 0.6
and wings 1.0
```

**Comment by parkervcp** [comment]
Wings is a beta. It's specifically tagged as such. I don't see this as an issue.

**Comment by parkervcp** [comment]
You install the the current version of the panel (0.7) and the current daemon (0.6).

Wings will eventually replace the old nodejs daemon.

**Comment by iamkubi** [comment]
Your arguments are not consistent.   Why hide the Panel 1.0 docs behind a dropdown but not the Wings 1.0?

**Comment by matthewpi** [comment]
Because the Panel is a direct upgrade/replacement while Wings is a completely new system.

But I do agree that Wings should be placed as a dropdown under the Daemon as it is basically a newer daemon written in another language, not to mention that the old daemon is referenced as `wings` in multiple places.  This would prevent people getting confused when they are installing Pterodactyl as it is not clear that you cannot run `wings` with the current stable panel and when follow the docs from the beginning it does not say that you need to install the daemon to run servers, leading people to potentially install none of them, both of them, or `wings` instead of the current daemon.

**Comment by DaneEveritt** [comment]
I think we could solve this by just making it very clear on the wings install page that it is beta software, and likely _not_ what the user is looking for.

I'm happy with the current documentation structure, but it might just need some language adjustments. I'm pretty tired of constantly changing things and making it more confusing for me to reason about and maintain just because people are too dense to slow down and read the directions.

However, if we're showing everything like this and there _is not_ a clear warning on the wings page then it should be added.
